server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/asagyn
    password: 123456
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:/config.liquibase/changelog-master.xml

security:
  authentication:
    jwt:
      base64-secret: ${JWT_SECRET:ODVjYWU2ZDUzYjI0NzhjNTc4NzZjYzY1ODc5Nzk4OGI3MWMzYjUzZWY5N2Y2MzAxYzRmMmQ3MGJhMDQ5NjQ4YzhmMWFiYmM0NTdmZmY1MjgwODczZmI4OWMzMzNlZjcyMmE1MzA5ODEyOTNiMDEyOTdiMjQ1M2FjNDMzNjZjODg=}
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000

